# Generated by Django 2.1.5 on 2020-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=128)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
