# Generated by Django 2.1.5 on 2020-07-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('continent', models.CharField(max_length=128)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_density', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cvd_death_rate', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Data_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cases', models.IntegerField()),
                ('total_cases', models.IntegerField()),
                ('cases_per_million', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_cases_per_million', models.DecimalField(decimal_places=3, max_digits=20)),
                ('deaths', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('deaths_per_million', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_deaths_per_million', models.DecimalField(decimal_places=3, max_digits=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Country')),
            ],
        ),
    ]
