# Generated by Django 2.1.5 on 2020-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail_data_country',
            name='cases',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detail_data_country',
            name='deaths',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detail_data_country',
            name='total_cases',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detail_data_country',
            name='total_deaths',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='detail_data_country',
            unique_together={('date', 'country')},
        ),
    ]
