# Generated by Django 2.1.5 on 2020-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200716_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.SlugField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
