# Generated by Django 2.1.5 on 2020-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200723_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_2digits_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
