# Generated by Django 2.1.5 on 2020-07-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_country_country_2digits_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_2digits_code',
        ),
    ]
