# Generated by Django 2.1.5 on 2020-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200725_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_2digits_code',
            field=models.CharField(default='ts', max_length=3),
        ),
    ]
